### ISSUE TITLE
Delta radius auto-calibration

### ISSUE THREAD

**Issue by clefranc** [clefranc/Marlin4Delta#14]
@thinkyhead Hi, can I ask you, during your break of MarlinDev development, help me (or should I say assist you), writing an automated calibration for the delta horizontal radius adjustment?

I have a vague idea on its implementation, should be fully automatic using the Z probe, or manual giving values to user for the radius (M665).

**Comment by thinkyhead** [comment]
My break has been longer than expected, sorry about that. I just rolled the formal 1.1.0-RC3 release the other day and am interested in shepherding that branch to the final 1.1.0 release. Meanwhile, if you're still interested in this idea and haven't already implemented it, I'd be interested in working on it with you within my own fork of Marlin for inclusion in the Marlin dev branch.
